workflows:
  version: 2
  build:
    name: Build APK with Debugging
    steps:
      - name: Checkout repository
        checkout: self
      - name: Set Permissions
        script: |
          cd android
          chmod +x gradlew
          chmod -R 755 .gradle
      - name: Refresh Dependencies
        script: |
          cd android
          ./gradlew --refresh-dependencies
      - name: Build APK with Debugging
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease --stacktrace --debug --info --warning-mode all
      - name: Dependency Analysis
        script: |
          cd android
          ./gradlew dependencies
