workflows:
  android-app:
    name: Build Android APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 17
      vars:
        JAVA_VERSION: 17
        GRADLE_VERSION: 8.13
    scripts:
      - name: Set up Java and Gradle
        script: |
          export JAVA_HOME=$(/usr/libexec/java_home -v 17)
          cd android
          chmod +x gradlew  # ✅ Fix permission issue
          ./gradlew --version  # Verify Gradle version
      - name: Set Gradle Version to 8.13
        script: |
          cd android
          ./gradlew wrapper --gradle-version=8.13 --distribution-type=bin  # Update Gradle wrapper to 8.13
      - name: Refresh Dependencies
        script: |
          cd android
          chmod +x gradlew  # Ensure permission before running again
          ./gradlew --refresh-dependencies  # Refresh project dependencies
      - name: Build APK
        script: |
          cd android
          chmod +x gradlew  # Just to be sure
          ./gradlew clean  # Clean the project
          ./gradlew assembleRelease --stacktrace --info --warning-mode all  # Build APK and show deprecation warnings
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
